package simulation;

import genome.Genome;

public class Carnivore extends Species{
	private String[] geneNames = {"size","speed","maxAge","scentRange"};
	private final int FOOD_DIGEST_TIME = 1000;
	boolean eating = false;
	private int timeSinceEating;
	private final int MINIMUM_REP_TIME = 2;

	//innitial constructor
	public Carnivore(int size, int speed, int maxAge) {
		super(size, speed, maxAge);
		this.timeSinceEating = 0;
	}
	
	//inheriting constructor
	public Carnivore(int x, int y,int energy, Genome genome, int number) {
		super(x, y, energy, genome, number);
		this.timeSinceEating = 0;
	}
	
	public double getEnergyConsumption() {
		int r = getSize() / 2;
		double contentSurface = (1.33* Math.PI * Math.pow(r, 3)) /(4 * Math.PI * Math.pow(r, 2));
		return (Math.pow(1.25, contentSurface) - 1)* 0.3* getSpeed() + 0.05*(getScentRange() - getSize()) + 0.5*getAge();
	}

	/**
	 * Function that will check if a eatable species is completely in the bounding box of the carnivore.
	 * If this is the case true is returned and the energy is added to the energy of the carnivore. This means
	 * that the species got eaten and will be removed from the game. The eating boolean will be set to true making
	 * carnivores slow so they cant effectively eat.
	 * @param x the x coordinate of the eatable species
	 * @param y the y coordinate of the eatable species
	 * @param size the sSize the size of the eatable species
	 * @param sEnergy the energy of the eatable species
	 * @return boolean that tells if the species can be eaten or not.
	 */
	public boolean checkCanEat(int x, int y, int sSize, int sEnergy) {
		if (getxLoc() - 0.5 * getSize() < x && getxLoc() + 0.5 * getSize() - 0.5 * sSize > x 
				&& getyLoc() - 0.5 * getSize()  < y && getyLoc() + 0.5 * getSize() - 0.5 * sSize > y) {
			changeEnergy(sEnergy);
			this.eating = true;
			return true;
		}
		return false;
	}
	
	public void useScentToMove(int ix, int iy) {
		double y  = (double) iy;
		double x = (double) ix;
		if (getEnergy() > 0 && !this.eating) {
			double slopeLength = Math.sqrt(Math.pow(x - getxLoc(), 2) + Math.pow(y - getyLoc(), 2));
			//direction that is straigh away from the target
			changeXLoc((x - getxLoc())/ slopeLength *getSpeed());
			changeYLoc((y - getyLoc())/ slopeLength * getSpeed());
			double fd = Math.atan2((y - getyLoc())/ slopeLength, (x - getxLoc())/ slopeLength);
			double min = (fd - 0.25 * Math.PI);
			double max = (fd + 0.25 * Math.PI);
			setFacingDirection((Math.random() * (max - min)) + min);
			changeEnergy(-1*getEnergyConsumption());
		}
		else {
			move();
		}
	}
	
	public void move() {
		eatTimeCheck();
		if (getEnergy() > 0) {
			double min = (getFacingDirection() - 0.25 * Math.PI);
			double max = (getFacingDirection() + 0.25 * Math.PI);
			setFacingDirection((Math.random() * (max - min)) + min);
			changeXLoc(Math.sin(getFacingDirection()) * getSpeed());
			changeYLoc((-1 * Math.cos(getFacingDirection()) * getSpeed()));
			changeEnergy(-1*getEnergyConsumption());			
		}
	}
	
	public void eatTimeCheck() {
		if (this.eating) {
			if (this.timeSinceEating == 0) {
				setSpeed(3);
			}
			this.timeSinceEating += 50;
			if (this.timeSinceEating >= this.FOOD_DIGEST_TIME) {
				this.eating = false;
				this.timeSinceEating = 0;
				setSpeed(getGenome().getGeneValue("speed"));
			}
		}
	}
	
	public String[] getGeneNames() {
		return this.geneNames;
	}
	
	public int getRepTime() { 
		return this.MINIMUM_REP_TIME;
	}
	
	/**
	 * Function that returns the size of an organism towards its maximum value generated by the genome depending on how old
	 * the organism is. The formula describing it looks like a michaels menten formula. But the start
	 * value is set to 25 procent of the maximum value.
	 */
	public int getSize() {
		return (int) (((getGenome().getGeneValue("size") - 0.5 * getGenome().getGeneValue("size")) * getAge()) /
				(getAge() + 5) + 0.5 * getGenome().getGeneValue("size"));
	}

}
